name: CI
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Node Version
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build
      run: |
        npm install -g @vercel/ncc@0.27.0
        npm install
        npm run build

    # - name: Push Dist
      # if: github.ref != 'refs/heads/main'
      # uses: EndBug/add-and-commit@v7
      # with:
        # author_name: github-actions
        # author_email: 41898282+github-actions[bot]@users.noreply.github.com
        # add: ./dist
        # pull_strategy: NO-PULL
        # push: true
