name: draft-release
on:
  push:
    branches: [ main ]

jobs:
  draft-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref  == 'refs/heads/main'
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Draft Release
      id: release_drafter
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
